version: '3.4'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - "./scripts/01-db-schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/02-sample-data.sql:/docker-entrypoint-initdb.d/2.sql"